# 给出一条DNA单链，求其互补链（反向）

str_A = """ACAGGAACTATTCTCACTGCTGTCCGCTGAACGCCTATACAGTAGCTTCTGTGTTTGGCAAGCGGTATGTACCGGCGTGTTTACGGGCTAACCGAGTTGAAGCTTAACGGCATATCCGAGGAATACGCGGGAGTTTGTGTTGTATCAGTTTATCCAAACCACAAATCTCCTCGTGGACAAACGATGATGACTGCTACACGGCGGTGCGCTTCTGCTATAAGTAAGCCTAACACTTGTACCTAGGTCTGTGATGGTACAGTCGCCCGCTAGGATCATACCTACTCAACCGCCAATTAATTAACTGGTAGTTCCAAACAAACCCTACTACTCACAACAAAAGGATACCGCCATACGTGGTGTGATACATCGTTGGACTAGAGATAGTTGGGACCAAAGCACACCCAAATGTGAACTTCTGTTAACTATTTTGGACTCTCCGGCAGAACTAGCTCGGCTCACCAATGTGAGAGGTGCCCTCCAGACCCGTATGCATCGCCTGGTAATCCTTGGTGAGACCATACGAACGGTCCGTCTCGGATTCCTGTAATATTATTTTTATACGCTATGGGACTCGGACAAATCCCCGGCGGAGACGCTCTGCCCGTTTACGTATACGCTTCCCGGGCGATCCCTGCCGGCGGCCGGAAAGCGACACTCTCAAGCTCTTCAGCATCCCGGACCATAAAGGTATGGGATCCGGTCTGTATTTTCGCAACTTTTCCCTAAGATCATTGCATCAAACCTCTTCTGATGACTGTCAGCATAAATCGAGGGTCTAAACCGCTCCATGTACCACATGACGAATCAGAGATAACCATGCTCAGAAAACCAAAATTATGGATAGCGAACAGTGGTGGAGATACCACGGTAAAGGGGTCCTAGATTATTGATCCCCTGGATGGCTTCTCCTCGATAGGTTTCTAGGCCGTATTCGCTTTTACTATTGGGATTCGTAGAAGGAACGG
"""

str_B = str_A.replace('A','S')
str_B = str_B.replace('C','F')
str_B = str_B.replace('G','B')
str_B = str_B.replace('T','Z')

str_B = str_B[::-1]

str_B = str_B.replace('S','T')
str_B = str_B.replace('F','G')
str_B = str_B.replace('B','C')
str_B = str_B.replace('Z','A')

print(str_B)


